config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :exams
  root 'home#index'
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get 'admin/exam/new'
  get 'home/sandbox'

  # match ':controller(/:action(/:id(.:format)))', :via => :get


end

app/models/exam.rb
class Exam < ActiveRecord::Base
  has_attached_file :recording, :default_url => "/images/:style/missing.png"
  do_not_validate_attachment_file_type :recording


  self.inheritance_column = nil
  extend Enumerize
  enumerize :type, in: ['Stationary','Pinch','Grab','Rotate','Trace']
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!



end

app/controllers/exams_controller.rb
class ExamsController < InheritedResources::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # @skip_nav = true
  end

  def test
    @skip_nav = true
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < InheritedResources::Base

  def new
    # @skip_nav = true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/exams/index.html.haml
%h1 Review Exams
%table.table-striped.table-hover.table-bordered
  %thead
    %tr
      %th.col-md-5 Patient Name
      %th.col-md-5 Exam Date
      %th.col-md-1 Edit
      %th.col-md-1 Delete
  %tbody
    - collection.each do |x|
      %tr
        %td.patient-name= x.patient
        %td= link_to x.created_at.to_s(:stat), x
        %td= link_to 'Edit', edit_exam_path(x)
        / %td= link_to 'Delete', :method =>:delete, :data => {:confirm => "Are you sure?"}

app/views/exams/show.html.haml
- content_for :header do
  :css
    body{
      font-family: Helvetica;
    }
    canvas {
      position: fixed;
      width: 100%;
      height: 100%;
      top: 0;
      left: 0;
    }
    #debugger{
      top: 0;
      left: 0;
      position: fixed;
      background: black;
      color: #eee;
      padding: 4px;
      display: none;
    }

%p
  %strong Patient Name:
  = resource.patient
%p
  %strong Recorded:
  = resource.created_at.to_s(:full)
%p
  %strong Exam Type:
  = resource.type
%p
  %strong Notes:
  = resource.notes
:javascript
  Leap.loop({})
    .use('playback', {
      recording: '#{resource.recording.url.gsub(/\?.*/, '')}',
      requiredProtocolVersion: 6,
      pauseOnHand: true,
      loop: true
    })
    .use('riggedHand');

  window.controller = Leap.loopController;

app/views/home/index.html.haml
/ =render template: 'layouts/application'

%br
%br
%br
%br
%br
.row
  .col-lg-12
    .well
      %h1{style: 'text-align: center'} Example of Hand Tremor
      .row
        .col-lg-12{style: 'text-align: center'}
          %iframe{src: "http://player.vimeo.com/video/77449238?title=0&amp;byline=0&amp;portrait=0&amp;color=ff9933", frameborder: 0, width: 500, height: 281, webkitallowfullscreen: true, mozallowfullscreen: true, allowfullscreen: true}
      %br
      .row
        .col-lg-6{style: 'text-align: center'}
          = link_to 'Review Exams', exams_path, class: 'btn btn-primary'
        .col-lg-6{style: 'text-align: center'}
          = link_to 'New Exam', '/admin/exam/new', class: 'btn btn-primary'
%br
%br
%br
.row
  .col-lg-12
    .row
      .col-lg-12
        =render partial: 'test'

app/views/home/sandbox.html.erb
<br>
<br>
<br>
<div id="output"></div>

<h1>Pinch Strength</h1>
<div id="pinch" style="height: 600px; width: 600px;"></div>

<h1>Grab Strength</h1>
<div id="grab" style="height: 600px; width: 600px;"></div>


<script type="text/javascript">



function concatData(id, data) {
  return id + ": " + data + "<br>";
}

var output = document.getElementById('output');
var frameString = "", handString = "";
// , fingerString = "";
var hand;
// , finger;

// Leap.loop uses browser's requestAnimationFrame
var options = {enableGestures: true};
// Main Leap loop
Leap.loop(options, function(frame) {
  frameString = concatData("frame_id", frame.id);
  frameString += concatData("num_hands", frame.hands.length);
  // frameString += concatData("frame_id", frame.fingers.length);
  frameString += "<br>";



  // hands
  for (var i=0, len=frame.hands.length; i<len; i++) {
    hand = frame.hands[i];
    handString = concatData("hand_type", hand.type);
    handString += concatData("pinch_strength", hand.pinchStrength);
    handString += concatData("grab_strength", hand.grabStrength);
    handString += concatData("confidence", hand.confidence);

    handString += "<br>";

    frameString += handString;
  }

  // getting data
  ps=[];
  gs=[];
  confidence=[];
  for (var i=0, len=frame.hands.length; i<len; i++) {
    hand = frame.hands[i];
    ps[i] = [i, hand.pinchStrength];
    gs[i] = [i, hand.grabStrength];
    confidence[i] = [i, hand.grabStrength];

    handString = concatData("hand_type", hand.type);
    handString += concatData("pinch_strength", hand.pinchStrength);
    handString += concatData("grab_strength", hand.grabStrength);
    handString += concatData("confidence", hand.confidence);

    handString += "<br>";

    frameString += handString;

  }


  // 60 fps
  // total_frames=frame.hands.length;
  // time=total_frames/60;

  // show output
  output.innerHTML = frameString;
  // output.innerHTML = ps;
  // How to get data from a recording?
  // Or how to keep data from live movement?
  new Chartkick.LineChart("pinch", ps);
  new Chartkick.LineChart("grab", gs);
});

</script>

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Hand Tremor Tracker"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = javascript_include_tag "//www.google.com/jsapi", "chartkick"

    = yield :header

  %body
    - unless @skip_nav
      .navbar.navbar-default.navbar-fixed-top
        .container-navbar
          %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          .navbar-brand= link_to "Hand Tremor Tracker", root_path
          .navbar-collapse.collapse.navbar-responsive-collapse
            -if user_signed_in?
              %ul.nav.navbar-nav
                %li= link_to 'Sandbox', 'home/sandbox'
                %li= link_to 'New Exam', rails_admin.new_path('exam'), method: :get
                %li= link_to 'Review Exams', rails_admin.index_path('exam'), method: :get
                %li= link_to 'Patients', '#'
                / %li.dropdown
                /   %a#themes.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                /     New Exam
                /     %span.caret
                /   %ul.dropdown-menu{"aria-labelledby" => "themes"}
                /     %li
                /       %a{:href => "../admin/exam/new"} Default
                /     %li.divider
                /     %li
                /       %a{:href => "../cerulean/"} Stationary
                /     %li
                /       %a{:href => "../cosmo/"} Pinch
                /     %li
                /       %a{:href => "../cyborg/"} Grab
                /     %li
                /       %a{:href => "../darkly/"} Rotate
                /     %li
                /       %a{:href => "../flatly/"} Trace
                / %li
                /   %a{:href => "../help/"} Help
              %ul.nav.navbar-nav.pull-right
                -if current_user && user_signed_in?
                  %li= link_to current_user.email
                  %li= link_to "Edit Account", edit_user_registration_path
                  %li= link_to "Logout", destroy_user_session_path, :method => :delete
                  %li.divider
                -else
                  %li= link_to "Log In", new_user_session_path
                  %li= link_to "Sign Up", new_user_registration_path
            -else



  / end of navbar

  .container
    .row
      .col-lg-12
        = bootstrap_flash
        = yield